### ISSUE TITLE
Home page missing image

### ISSUE THREAD

**Issue by bartonhammond** [jon49/cash#3]
<img width="577" alt="Screenshot 2024-12-30 at 11 46 47 AM" src="https://github.com/user-attachments/assets/a7ff43ec-5e97-49eb-95a3-7d7abf4dbf1d" />

**Comment by jon49** [comment]
Oh, yes, you can download the images here and put them in the `pb_public/web/images` directory:

https://cash.jnyman.com/web/images/cash.svg
https://cash.jnyman.com/web/images/cash.ico
https://cash.jnyman.com/web/images/cash.png

**Comment by jon49** [comment]
Documentation has been added for image downloading into the project.
